# Generated by Django 2.1.1 on 2018-10-21 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_ownerinfo_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furnish',
            name='fully',
        ),
        migrations.RemoveField(
            model_name='furnish',
            name='partially',
        ),
        migrations.RemoveField(
            model_name='furnish',
            name='unfurnished',
        ),
        migrations.AddField(
            model_name='furnish',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Bhk'),
        ),
    ]
