# Generated by Django 2.1.1 on 2018-10-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20181021_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Furnish',
            new_name='PropertyStatus',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='furnish',
            new_name='property_status',
        ),
    ]
